#!/bin/bash
# configure WPE WebKit against silver's install
I=/src/silver/install
cd /src/silver/checkout/wk/wpewebkit-2.54.0
export PATH=$I/bin:$PATH PKG_CONFIG_PATH=$I/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
cmake -S . -B build -G Ninja -DPORT=WPE -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=$I "-DCMAKE_INSTALL_RPATH=$I/lib;$I/build" -DCMAKE_PREFIX_PATH=$I \
  -DCMAKE_C_COMPILER=$I/bin/clang -DCMAKE_CXX_COMPILER=$I/bin/clang++ \
  -DSILVER_INSTALL=$I \
  -DENABLE_XSLT=OFF -DENABLE_SPEECH_SYNTHESIS=OFF -DUSE_AVIF=OFF -DUSE_LCMS=OFF \
  -DUSE_JPEGXL=OFF -DUSE_WOFF2=OFF -DUSE_ATK=OFF -DENABLE_INTROSPECTION=OFF \
  -DENABLE_DOCUMENTATION=OFF -DENABLE_JOURNALD_LOG=OFF -DENABLE_WEBDRIVER=OFF \
  -DENABLE_BUBBLEWRAP_SANDBOX=OFF -DENABLE_WPE_LEGACY_API=OFF \
  -DENABLE_WPE_PLATFORM_WAYLAND=OFF -DENABLE_WPE_PLATFORM_DRM=OFF \
  -DENABLE_VIDEO=ON -DENABLE_WEB_AUDIO=OFF -DUSE_LIBBACKTRACE=OFF \
  -DENABLE_GAMEPAD=OFF -DUSE_LIBHYPHEN=OFF -DENABLE_WEB_CODECS=OFF \
  -DENABLE_MEDIA_STREAM=OFF -DENABLE_WEB_RTC=OFF -DENABLE_SPELLCHECK=OFF -DUSE_GSTREAMER=OFF -DUSE_GSTREAMER_WEBRTC=OFF -DENABLE_ENCRYPTED_MEDIA=OFF -DENABLE_MEDIA_SOURCE=ON -DUSE_SYSTEM_SYSPROF_CAPTURE=NO -DUSE_SYSPROF_CAPTURE=OFF -DUSE_SKIA_OPENTYPE_SVG=OFF "$@"
