#include <e-nodes.h>

/*
num Token_compare(Token a, Token b) {
    return call(a->value, compare, b->value);
}

bool32 Token_cast_bool32(Token a) {
    return cast(a->value, bool32);
}

define_class(ENode)
define_class(EContext)
define_mod(EIdent,              ENode)
define_mod(EModule,             ENode)
define_mod(EMember,             ENode)
define_mod(EMetaMember,         EMember)
define_mod(EMethod,             EMember)
define_mod(EClass,              EMember)
define_mod(EProp,               EMember)
define_mod(EStruct,             EMember)
define_mod(EOperator,           ENode)
define_mod(ECompareEquals,      EOperator)
define_mod(ECompareNotEquals,   EOperator)
define_mod(EAdd,                EOperator)
define_mod(ESub,                EOperator)
define_mod(EMul,                EOperator)
define_mod(EDiv,                EOperator)
define_mod(EOr,                 EOperator)
define_mod(EAnd,                EOperator)
define_mod(EXor,                EOperator)
define_mod(EIs,                 EOperator)
define_mod(EInherits,           EIs)
define_mod(EImport,             ENode)
define_mod(EStatements,         ENode)
define_mod(EModel,              ENode)
define_mod(EDeclaration,        ENode)
define_mod(EConstruct,          ENode)
define_mod(EExplicitCast,       ENode)
define_mod(EPrimitive,          ENode)
define_mod(EUndefined,          ENode)
define_mod(EParenthesis,        ENode)
define_mod(ELogicalNot,         ENode)
define_mod(EBitwiseNot,         ENode)
define_mod(ERef,                ENode)
define_mod(ERefCast,            ENode)
define_mod(EIndex,              ENode)
define_mod(EAssign,             ENode)
define_mod(EAssignAdd,          EAssign)
define_mod(EAssignSub,          EAssign)
define_mod(EAssignMul,          EAssign)
define_mod(EAssignDiv,          EAssign)
define_mod(EAssignOr,           EAssign)
define_mod(EAssignAnd,          EAssign)
define_mod(EAssignXor,          EAssign)
define_mod(EAssignShiftR,       EAssign)
define_mod(EAssignShiftL,       EAssign)
define_mod(EAssignMod,          EAssign)
define_mod(EIf,                 ENode)
define_mod(EFor,                ENode)
define_mod(EWhile,              ENode)
define_mod(EDoWhile,            ENode)
define_mod(EBreak,              ENode)
define_mod(ELiteralReal,        ENode)
define_mod(ELiteralInt,         ENode)
define_mod(ELiteralStr,         ENode)
define_mod(ELiteralStrInterp,   ENode)
define_mod(ELiteralBool,        ENode)
define_mod(ESubProc,            ENode)
define_mod(ERuntimeType,        ENode)
define_mod(EMethodCall,         ENode)
define_mod(EMethodReturn,       ENode)

*/